name: Launch Tracker CI
on: # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: # Job1 called build

    env:
      CI: true
    strategy:
      matrix: # 2 build jobs run in parallel
        node-version: [14.x, 16.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Use NodeJS version ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: ${{ matrix.node-version }}

      - run: npm run install-all
      - run: npm run deploy